allprojects {
    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    dependencies {
        // Source: https://mvnrepository.com/artifact/com.zeroc/ice
        implementation 'com.zeroc:ice:3.7.11'
    }
}